import type { Metadata } from "next";
import Header from "@/components/home/header";
import Footer from "@/components/home/footer";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`antialiased`}>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
